Home page made into react
HarshithaKonduru214/pulse-ecom pull request #1
Opened 2022-03-23 19:01 UTC by HarshithaKonduru214

Pls review my home page.

https://merry-sopapillas-e67bb9.netlify.app/

2022-03-23 19:21 UTC, HarshithaKonduru214 commented
https://merry-sopapillas-e67bb9.netlify.app/

2022-03-23 19:59 UTC, Rohitprasad83 commented
I think you forgot to put the node modules into git ignore file, because there are 5000+ files changed

2022-03-24 15:38 UTC, NtshVrm requested changes
Apart from the suggested changes, 
- File Structure is great
- Broken down into neat components💯

Good job 👏

2022-03-24 15:38 UTC, NtshVrm commented on src/backend/db/categories.js
> +import women from "../../images/women.jpg";
Recommend using barrel importing for images

2022-03-24 15:38 UTC, NtshVrm commented on src/components/SocialMedia.jsx
> +import { Social } from "./Social"
since you've created an index file that exports all components you can import your components from there for consistency

2022-03-24 15:38 UTC, NtshVrm commented on src/pages/Home/Home.jsx
> +import { Banner } from "../../components/Banner";
similar change as before i.e. barrel import from index.js

2022-03-25 11:22 UTC, closed without merging